config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :questions
  resources :mycontacts
  get 'messages/index'
  get 'messages', to: 'messages#index'
  
  get 'messages/add'
  post 'messages/add', to: 'messages#create'
  
  get 'messages/edit/:id', to: 'messages#edit'
  patch 'messages/edit/:id', to: 'messages#update'
  
  get 'messages/delete/:id', to: 'messages#delete'
  get 'messages/:id', to: 'messages#show'

  get 'cards/index'
  get 'cards', to: 'cards#index'
  
  get 'cards/add'
  post 'cards/add'
  
  get 'cards/:id', to: 'cards#show'
  
  get 'cards/edit/:id', to: 'cards#edit'
  patch 'cards/edit/:id', to: 'cards#edit'
  
  get 'cards/delete/:id', to: 'cards#delete'

  get 'people/index'
  get 'people', to: 'people#index'
  get 'people/find'
  post 'people/find'
  get 'people/add'
  post 'people/add', to: 'people#create'
  get 'people/:id', to: 'people#show'
  get 'people/edit/:id', to: 'people#edit'
  post 'people/edit/:id', to: 'people#update'
  patch 'people/edit/:id', to: 'people#update'
  get 'people/delete/:id', to: 'people#delete'

  get 'msgboard', to: 'msgboard#index'
  post 'msgboard', to: 'msgboard#index'

  get 'msgboard/index'
  post 'msgboard/index'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'hello/index'
  get 'hello', to: 'hello#index'
  get 'hello/other'

  post 'hello/index'
  post 'hello', to: 'hello#index'
end

app/models/mycontact.rb
class Mycontact < ApplicationRecord
    validates :name, presence: { message:'は、必須項目です。' }
    validates :age, numericality: { message:'は、数字で入力してください。' }
    validates :nationality, inclusion: { in: [true, false], message:'は、真偽値です。'}
end

app/controllers/mycontacts_controller.rb
class MycontactsController < ApplicationController
  before_action :set_mycontact, only: %i[ show edit update destroy ]

  # GET /mycontacts or /mycontacts.json
  def index
    @mycontacts = Mycontact.all
  end

  # GET /mycontacts/1 or /mycontacts/1.json
  def show
  end

  # GET /mycontacts/new
  def new
    @mycontact = Mycontact.new
  end

  # GET /mycontacts/1/edit
  def edit
  end

  # POST /mycontacts or /mycontacts.json
  def create
    @mycontact = Mycontact.new(mycontact_params)

    respond_to do |format|
      if @mycontact.save
        format.html { redirect_to mycontact_url(@mycontact), notice: "Mycontact was successfully created." }
        format.json { render :show, status: :created, location: @mycontact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mycontacts/1 or /mycontacts/1.json
  def update
    respond_to do |format|
      if @mycontact.update(mycontact_params)
        format.html { redirect_to mycontact_url(@mycontact), notice: "Mycontact was successfully updated." }
        format.json { render :show, status: :ok, location: @mycontact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mycontact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mycontacts/1 or /mycontacts/1.json
  def destroy
    @mycontact.destroy!

    respond_to do |format|
      format.html { redirect_to mycontacts_url, notice: "Mycontact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mycontact
      @mycontact = Mycontact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mycontact_params
      params.require(:mycontact).permit(:name, :age, :nationality, :mail)
    end
end

app/helpers/mycontacts_helper.rb
module MycontactsHelper
end

app/views/mycontacts/_form.html.erb
<%= form_with(model: mycontact) do |form| %　>
  <% if mycontact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mycontact.errors.count, "error") %> prohibited this mycontact from being saved:</h2>

      <ul>
        <% mycontact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.label :nationality, style: "display: block" %>
    <%= form.check_box :nationality %>
  </div>

  <div>
    <%= form.label :mail, style: "display: block" %>
    <%= form.text_area :mail %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/mycontacts/_mycontact.html.erb
<div id="<%= dom_id mycontact %>">
  <p>
    <strong>Name:</strong>
    <%= mycontact.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= mycontact.age %>
  </p>

  <p>
    <strong>Nationality:</strong>
    <%= mycontact.nationality %>
  </p>

  <p>
    <strong>Mail:</strong>
    <%= mycontact.mail %>
  </p>

</div>

app/views/mycontacts/edit.html.erb
<h1>Editing mycontact</h1>

<%= render "form", mycontact: @mycontact %>

<br>

<div>
  <%= link_to "Show this mycontact", @mycontact %> |
  <%= link_to "Back to mycontacts", mycontacts_path %>
</div>

app/views/mycontacts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Mycontacts</h1>

<div id="mycontacts">
  <% @mycontacts.each do |mycontact| %>
    <%= render mycontact %>
    <p>
      <%= link_to "Show this mycontact", mycontact %>
    </p>
  <% end %>
</div>

<%= link_to "New mycontact", new_mycontact_path %>

app/views/mycontacts/new.html.erb
<h1>New mycontact</h1>

<%= render "form", mycontact: @mycontact %>

<br>

<div>
  <%= link_to "Back to mycontacts", mycontacts_path %>
</div>

app/views/mycontacts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @mycontact %>

<div>
  <%= link_to "Edit this mycontact", edit_mycontact_path(@mycontact) %> |
  <%= link_to "Back to mycontacts", mycontacts_path %>

  <%= button_to "Destroy this mycontact", @mycontact, method: :delete %>
</div>